apiVersion: v1
kind: Pod
metadata:
  name: zabbix-srv
  labels:
    app: zabbix-app
spec:
  containers:
    - name: zabbix-container
      image: zabbix/zabbix-server-pgsql
      env:
      - name: POSTGRES_USER
        value: zabbix
      - name: ZBX_SERVER_HOST
        value: zabbix-svc-int
      - name: ZBX_SERVER_PORT
        value: '10050'
      - name: DB_SERVER_HOST
        value: zabbix-svc-int
      - name: DB_SERVER_PORT
        value: '5432'