apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix
  labels:
    app: zabbix-app
    type: frontend
spec:
  template:
    metadata:
      name: zabbix-pod
      labels:
        app: zabbix-app
        type: frontend
    spec:
      containers:
        - name: zabbix-container
          image: zabbix/zabbix-web-nginx-pgsql
          env:
            - name: POSTGRES_USER
              value: zabbix
            - name: ZBX_SERVER_HOST
              value: zabbix-svc-int
            - name: ZBX_SERVER_PORT
              value: '10050'
            - name: DB_SERVER_HOST
              value: zabbix-svc-int
            - name: DB_SERVER_PORT
              value: '5432'
  selector:
    matchLabels:
      type: frontend
  replicas: 3